### PR TITLE
Flask blueprint tweaks

### PR DESCRIPTION
**Pull request by robinandeer**
It's now finally time to start the integration process of Pybamview into our own server :smile: 

While I looked into this I came a across a few additional updates/simplifications that makes the transition to Blueprint-based structure (hopefully) complete.

This PR contains updates to:

- move all assets into the actual blueprint module so that they can be move with the Blueprint
- Flask then also wants us to specify explicitly from which folder we grab static files ``url_for('browser.static', filename=...)``
- add also a default for the ``LOADCHAR`` which is usually provided through the CLI
- rename the "static" directory to something more descriptive; "img".

### CODE REVIEW

**Comment by robinandeer** [comment]
Having some slight problems with the static assets. I will probably append a few commits before this PR is ready for possible merge.

**Comment by robinandeer** [comment]
That should hopefully do it. I believe Flask expects Blueprints that ship with included assets to be defined under a specific url prefix. The workaround is to point the main Flask app object to the Blueprint templates/static files.

Perhaps at some point it would make sense to split the single Blueprint into two more separate Blueprint modules.

**Comment by mgymrek** [comment]
Sorry for taking a while to get to this. Looks great. Thanks again!

**Comment by robinandeer** [comment]
Actually, this is perfect timing! We are just prepping our first release :smile:

**Pull request merged**
